import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Carsly",
  description: "Generated by Znackt",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-black selection:text-white`}
      >
        <SidebarProvider>
          <AppSidebar />
          
          {/* 
            FIX 1: Added flex-col and h-screen so the topbar stays put 
            while the dashboard content scrolls independently 
          */}
          <main className="flex flex-1 flex-col w-full h-screen overflow-hidden">
            
            {/* 
              FIX 2: Made the mobile topbar a fixed height (h-14) 
              and added shrink-0 so it never squishes 
            */}
            <div className="md:hidden flex h-14 items-center border-b border-gray-200 bg-white px-4 shrink-0 shadow-sm z-10">
              <SidebarTrigger />
            </div>
            
            {/* 
              FIX 3: Wrapped children in an overflow-y-auto container 
              and added pt-6 md:pt-8 to give the dashboard breathing room at the top 
            */}
            <div className="flex-1 overflow-y-auto pt-6 md:pt-8">
              {children}
            </div>
            
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}